//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PaginaRecetasEntities2 : DbContext
    {
        public BD_PaginaRecetasEntities2()
            : base("name=BD_PaginaRecetasEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<COMENTARIOS> COMENTARIOS { get; set; }
        public virtual DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public virtual DbSet<MULTIMEDIA> MULTIMEDIA { get; set; }
        public virtual DbSet<RECETAS> RECETAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
