//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PaginaRecetasEntities2 : DbContext
    {
        public BD_PaginaRecetasEntities2(string con)
            : base(con)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<COMENTARIOS> COMENTARIOS { get; set; }
        public virtual DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public virtual DbSet<MULTIMEDIA> MULTIMEDIA { get; set; }
        public virtual DbSet<RECETAS> RECETAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
