//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RecetasEntities : DbContext
    {
        public DB_RecetasEntities()
            : base("name=DB_RecetasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<Ingrediente> Ingredientes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipos_Recetas> Tipos_Recetas { get; set; }
        public virtual DbSet<Unidade> Unidades { get; set; }
        public virtual DbSet<Ingrediente_Receta> Ingrediente_Receta { get; set; }
        public virtual DbSet<tablaPrincipal> tablaPrincipals { get; set; }
    }
}
