//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente_Receta
    {
        public double Cantidad { get; set; }
        public int ID_Receta { get; set; }
        public int ID_Unidad { get; set; }
        public int ID_Ingrediente { get; set; }
    
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Receta Receta { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
