//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTES
    {
        public int ID_Ingrediente { get; set; }
        public int ID_Receta { get; set; }
        public string Ingrediente { get; set; }
    
        public virtual RECETAS RECETAS { get; set; }
    }
}
