//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Receta
    {
        public Receta()
        {
            Nivel = 1;
            Activo = true;
            Fecha_Baja = null;
            Fecha_Alta = DateTime.Today;
        }
        public int ID_Recetas { get; set; }
        public string Nombre { get; set; }
        public string Instrucciones { get; set; }
        public Nullable<int> Nivel { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public string Imagen { get; set; }
        public string Video { get; set; }
        [DisplayName("Usuario")]
        public int ID_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
