//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablaPrincipal
    {
        public int ID_Usuario { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> ID_TipoReceta { get; set; }
        public int Expr2 { get; set; }
        public string Tipo_Receta { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public string Expr3 { get; set; }
    }
}
