//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaRecetas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Recetas = new HashSet<Receta>();
            Nivel = 1;
            Activo = true;
        }
    
        public int ID_Usuario { get; set; }
        [Required(ErrorMessage ="Campo Nombre Obligatorio")]
        public string Nombre { get; set; }
        
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "Campo Correo Obligatorio")]
        public string Correo { get; set; }
        [DisplayName("Contraseña")]
        [Required(ErrorMessage = "Campo Contraseña Obligatorio")]
        public string Contrasenia { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> Nivel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
    }
}
